### ISSUE TITLE
RBFMeshMotionSolver with interfoam

### ISSUE THREAD

**Issue by NUGUY2022** [NikolausKurcz/mem4py_adapter#2]
Hi Niko,
I have checked your coupling model and find that you use the RBFMeshMotionSolver with pimpleFoam.  However, I want to use RBF with InterFoam. Through some case tests, it seems that RBF can't be used with interFoam. Do you have any experience and advice about employing RBF in interFoam?

**Comment by NikolausKurcz** [comment]
Hi Nuguy,

Sorry I have no experience with it

**Comment by NUGUY2022** [comment]
Thank you, Niko.
